// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseMicroservice.DBContexts;

namespace PurchaseMicroservice.Migrations
{
    [DbContext(typeof(PurchaseDbContext))]
    partial class PurchaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PurchaseMicroservice.Entities.Purchase", b =>
                {
                    b.Property<Guid>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemForSaleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = new Guid("36e745c1-8615-4244-bf16-492b6493602f"),
                            AccountId = new Guid("7e58590d-3968-4730-9c62-1ce5ae071478"),
                            Date = "05/29/2021",
                            DeliveryId = new Guid("e04ce688-4fe1-43a1-838e-e3aedbe083b8"),
                            Description = "Cash on delivery",
                            ItemForSaleId = new Guid("915510b2-74fb-44b7-b265-730ac0079a0d")
                        },
                        new
                        {
                            PurchaseId = new Guid("ac770b34-0a5f-46f4-b5d0-7c4a7ce3a036"),
                            AccountId = new Guid("1265bcd7-6e5a-491b-b802-acf4c4646d78"),
                            Date = "06/11/2021",
                            DeliveryId = new Guid("bea55668-1ab8-4aa7-aca3-9b184f2c80d1"),
                            Description = "Cash on delivery",
                            ItemForSaleId = new Guid("972379ca-7d10-4741-9b61-90414c77f32d")
                        },
                        new
                        {
                            PurchaseId = new Guid("fc953708-ce8b-4925-bc2e-a1ef4b8fc932"),
                            AccountId = new Guid("bcac549f-188c-415b-b64f-6ac5545a3c17"),
                            Date = "06/07/2021",
                            DeliveryId = new Guid("f3c1d7f0-f973-4e11-9d99-35bf23f88304"),
                            Description = "Cash on delivery",
                            ItemForSaleId = new Guid("fe7a9096-80f4-4b7f-a8c3-0029be9959b7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
