// <auto-generated />
using System;
using MediaMicroservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaMicroservice.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaMicroservice.Entities.Media", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemForSaleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaId");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            MediaId = new Guid("11b74292-ff41-4ecd-873c-f81fd88692fe"),
                            AccountId = new Guid("f2d8362a-124f-41a9-a22b-6e35b3a2953c"),
                            FilePath = "https://static.tehnomanija.rs/UserFiles/products/2019/006/large/137147.webp",
                            ItemForSaleId = new Guid("4f29d0a1-a000-4b56-9005-1a40ffcea3ae")
                        },
                        new
                        {
                            MediaId = new Guid("91cc2b07-a231-4fe7-bf3b-48821e35c904"),
                            AccountId = new Guid("1bc6929f-0e75-4bef-a835-7dbb50d9e41a"),
                            FilePath = "https://www.stevensbikes.de/2019/img/slider_res/jazz_gent_19_55_slate_grey_my19.jpg",
                            ItemForSaleId = new Guid("86f5ae7c-ef07-4339-9f46-c8f597560565")
                        },
                        new
                        {
                            MediaId = new Guid("6a21bf33-1b44-4846-975c-e91a9fba0203"),
                            AccountId = new Guid("b1d1e043-85c9-4ee1-9eb7-38314c109607"),
                            FilePath = "https://static.sredime.rs/image/photo/1/b/1b9f38268c50805669fd8caf8f3cc84a/3574_lg.jpg",
                            ItemForSaleId = new Guid("1f4aa5b3-a67f-45c5-b519-771a7c09a944")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
